-- Schema tối thiểu để test migration 20261003_dinh_ky_don_phan_du.sql
-- (hàm dinh_ky_don_phan_du + trigger trg_dinh_ky_don_phan_du + bước dọn dữ liệu).
-- Chạy trong DATABASE RIÊNG (dinh_ky_test) vì bộ recalc_chi_phi_payment_status
-- dùng chung tên bảng doan_chi_phi/de_nghi_thanh_toan nhưng ít cột hơn.

-- Role là đối tượng cấp cluster — bộ create_lead_from_form có thể đã tạo trước.
DO $$ BEGIN CREATE ROLE anon;          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE authenticated; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE service_role;  EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- auth.uid() giả: đọc GUC test.uid để test giả lập người đăng nhập (mặc định NULL
-- như lúc migration / service_role chạy).
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('test.uid', true), '')::uuid
$$;

CREATE TABLE user_roles (
  user_id uuid PRIMARY KEY,
  chi_xem boolean NOT NULL DEFAULT false
);

-- Bản sao hàm prod (20260728_tai_khoan_chi_xem).
CREATE OR REPLACE FUNCTION public.is_tk_chi_xem()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles ur
    WHERE ur.user_id = auth.uid() AND ur.chi_xem
  );
$$;

CREATE TABLE doan (
  id bigint PRIMARY KEY,
  ten_doan text,
  ngay_di date,
  trang_thai text NOT NULL DEFAULT 'dang_chay'
);

CREATE TABLE doan_chi_phi (
  id bigint PRIMARY KEY,
  doan_id bigint REFERENCES doan(id),
  nha_cung_cap_id bigint,
  don_gia numeric DEFAULT 0,
  so_luong numeric DEFAULT 1,
  thanh_tien numeric GENERATED ALWAYS AS (don_gia * so_luong) STORED,
  tien_cong_ty numeric DEFAULT 0,
  thanh_tien_thuc_te numeric,
  so_tien_da_dntt numeric DEFAULT 0,
  so_tien_da_tt numeric DEFAULT 0,
  trang_thai_thanh_toan text DEFAULT 'unpaid',
  trang_thai_dntt text DEFAULT 'chua_gui',
  thanh_toan_dinh_ky boolean DEFAULT false,
  ks_huy boolean NOT NULL DEFAULT false,
  ky_thanh_toan text,
  ngoai_tour boolean DEFAULT false,
  ngoai_tour_ci date
);

CREATE TABLE de_nghi_thanh_toan (
  id bigint PRIMARY KEY,
  doan_id bigint,
  loai text NOT NULL,
  ref_loai text,
  nha_cung_cap_id bigint,
  so_tien numeric NOT NULL DEFAULT 0,
  trang_thai_duyet text NOT NULL DEFAULT 'cho_duyet'
    CHECK (trang_thai_duyet IN ('cho_duyet', 'da_duyet', 'tu_choi', 'da_huy')),
  ghi_chu text
);

-- Như prod: id identity + CHECK so_tien > 0 + UNIQUE INDEX (không phải constraint).
CREATE TABLE dntt_allocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dntt_id bigint NOT NULL REFERENCES de_nghi_thanh_toan(id) ON DELETE CASCADE,
  chi_phi_id bigint NOT NULL REFERENCES doan_chi_phi(id) ON DELETE CASCADE,
  so_tien numeric CHECK (so_tien > 0),
  ghi_chu text
);
CREATE UNIQUE INDEX dntt_allocations_dntt_chi_phi_idx ON dntt_allocations (dntt_id, chi_phi_id);

CREATE TABLE payments (
  id bigserial PRIMARY KEY,
  dntt_id bigint NOT NULL REFERENCES de_nghi_thanh_toan(id) ON DELETE CASCADE,
  so_tien numeric NOT NULL
);

CREATE TABLE cong_no (
  id bigserial PRIMARY KEY,
  doan_id bigint,
  dntt_goc_id bigint,
  nha_cung_cap_id bigint,
  so_tien_goc numeric
);

CREATE TABLE activity_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid,
  ho_ten text,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text,
  mo_ta text,
  created_at timestamptz DEFAULT now(),
  doan_id integer
);
