
CREATE TABLE IF NOT EXISTS public.doan_booking_nh (
  id bigint generated by default as identity primary key,
  doan_id bigint not null,
  doan_ngay_id bigint not null,
  bua_an text not null check (bua_an in ('trua', 'toi')),
  nha_hang_id bigint,
  set_menu_id bigint,
  ten_set_snapshot text,
  gia_snapshot numeric,
  don_vi_snapshot text default 'VND',
  mon_an_snapshot jsonb default '[]'::jsonb,
  ghi_chu text,
  booking_status text not null default 'chua_gui',
  sent_at timestamptz,
  sent_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  UNIQUE(doan_ngay_id, bua_an)
);
