-- ================================================================
-- Migration: dntt_allocations
-- Mục đích: Thêm bảng phân bổ thanh toán theo đúng kiến trúc
--           payment_allocations trong claude.md
-- Chạy trong Supabase SQL Editor
-- ================================================================

-- ── 1. Tạo bảng ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.dntt_allocations (
  id          bigint generated by default as identity primary key,
  dntt_id     bigint not null
                references public.de_nghi_thanh_toan(id) on delete cascade,
  chi_phi_id  bigint not null
                references public.doan_chi_phi(id) on delete cascade,
  so_tien     numeric not null check (so_tien > 0),
  ghi_chu     text,
  created_at  timestamptz not null default now()
);

-- Một DNTT không thể phân bổ cho cùng một chi_phi hai lần
CREATE UNIQUE INDEX IF NOT EXISTS dntt_allocations_dntt_chi_phi_idx
  ON public.dntt_allocations (dntt_id, chi_phi_id);

-- Index tra cứu ngược: chi_phi → các DNTT phân bổ cho nó
CREATE INDEX IF NOT EXISTS dntt_allocations_chi_phi_id_idx
  ON public.dntt_allocations (chi_phi_id);

-- ── 2. Row-Level Security ─────────────────────────────────────────

ALTER TABLE public.dntt_allocations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read"
  ON public.dntt_allocations FOR SELECT USING (true);

CREATE POLICY "Allow public insert"
  ON public.dntt_allocations FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update"
  ON public.dntt_allocations FOR UPDATE USING (true);

CREATE POLICY "Allow public delete"
  ON public.dntt_allocations FOR DELETE USING (true);

-- ── 3. Migrate dữ liệu hiện có ───────────────────────────────────
-- Chỉ migrate DNTT có ref_loai = 'doan_chi_phi' (liên kết trực tiếp 1:1).
-- DNTT loại 'khach_san' không migrate tự động vì ref_id là khach_san.id,
-- không phải doan_chi_phi.id — các bản ghi mới sẽ có allocation từ đây trở đi.

INSERT INTO public.dntt_allocations (dntt_id, chi_phi_id, so_tien)
SELECT
  d.id      AS dntt_id,
  d.ref_id  AS chi_phi_id,
  d.so_tien AS so_tien
FROM public.de_nghi_thanh_toan d
WHERE
  d.ref_loai = 'doan_chi_phi'
  AND d.ref_id IS NOT NULL
  -- Idempotent: bỏ qua nếu đã có
  AND NOT EXISTS (
    SELECT 1 FROM public.dntt_allocations a
    WHERE a.dntt_id = d.id AND a.chi_phi_id = d.ref_id
  );

-- ── 4. Kiểm tra sau khi chạy ─────────────────────────────────────
-- Số dòng trong dntt_allocations phải bằng số DNTT có ref_loai='doan_chi_phi':
--
-- SELECT COUNT(*) FROM dntt_allocations;
-- SELECT COUNT(*) FROM de_nghi_thanh_toan
--   WHERE ref_loai = 'doan_chi_phi' AND ref_id IS NOT NULL;
